# Generated by Django 5.2.8 on 2025-11-08 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['name'], 'verbose_name_plural': 'Employees'},
        ),
    ]
